type: DeconvEncoder
args:
  layer: UpsamplingConvBlock
  channels: [16,32,64,128]
  kernel_size: [5,5,5]
  norm: pixel
  bias: False
  block_args:
    upsample: 2
    n_convs_per_block: 2
  nn_lin: LeakyReLU
  out_nnlin: Sigmoid
