defaults:
  - generator/adv_upsample_conv
  - discriminator/adv_downsample_conv

type: ModulatedGAN
latent:
  dist: Normal
encoder:
  type: MLPEncoder
  mode: sequential
  args:
    nlayers: 2
    target_shape: &mod_input 128
    norm: batch
    normalize: True
generator:
  args:
    layer: ModUpsamplingBlock
    mode: skip
    block_args:
      mod_input: *mod_input
discriminator:
  args:
    mode: residual
    flatten_args:
      nlayers: 0

